# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	addr2line@0.24.2
	adler2@2.0.1
	aho-corasick@1.1.3
	async-stream-impl@0.3.6
	async-stream@0.3.6
	async-trait@0.1.88
	atty@0.2.14
	autocfg@1.5.0
	backtrace@0.3.75
	bitflags@1.3.2
	bitflags@2.9.1
	bytes@1.10.1
	cfg-if@1.0.1
	crossbeam-utils@0.8.21
	dashmap@5.5.3
	dashmap@6.1.0
	env_logger@0.10.2
	fluent-uri@0.1.4
	futures-channel@0.3.31
	futures-core@0.3.31
	futures-io@0.3.31
	futures-macro@0.3.31
	futures-sink@0.3.31
	futures-task@0.3.31
	futures-util@0.3.31
	futures@0.3.31
	gimli@0.31.1
	hashbrown@0.14.5
	hermit-abi@0.1.19
	hermit-abi@0.5.2
	httparse@1.10.1
	humantime@2.2.0
	io-uring@0.7.8
	is-terminal@0.4.16
	itoa@1.0.15
	libc@0.2.174
	lock_api@0.4.13
	log@0.4.27
	lsp-types@0.97.0
	memchr@2.7.5
	miniz_oxide@0.8.9
	mio@1.0.4
	object@0.36.7
	once_cell@1.21.3
	parking_lot@0.12.4
	parking_lot_core@0.9.11
	percent-encoding@2.3.1
	pin-project-lite@0.2.16
	pin-utils@0.1.0
	proc-macro2@1.0.95
	quote@1.0.40
	redox_syscall@0.5.13
	regex-automata@0.4.9
	regex-syntax@0.8.5
	regex@1.11.1
	rustc-demangle@0.1.25
	ryu@1.0.20
	scopeguard@1.2.0
	serde@1.0.219
	serde_derive@1.0.219
	serde_json@1.0.140
	serde_repr@0.1.20
	signal-hook-registry@1.4.5
	slab@0.4.10
	smallvec@1.15.1
	socket2@0.5.10
	syn@2.0.104
	sync_wrapper@1.0.2
	termcolor@1.4.1
	thiserror-impl@1.0.69
	thiserror@1.0.69
	tokio-macros@2.5.0
	tokio-stream@0.1.17
	tokio-test@0.4.4
	tokio-util@0.7.15
	tokio@1.46.1
	tower-layer@0.3.3
	tower-lsp-server@0.22.0
	tower-service@0.3.3
	tower@0.5.2
	tracing-attributes@0.1.30
	tracing-core@0.1.34
	tracing@0.1.41
	unicode-ident@1.0.18
	wasi@0.11.1+wasi-snapshot-preview1
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.9
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.52.0
	windows-sys@0.59.0
	windows-targets@0.52.6
	windows_aarch64_gnullvm@0.52.6
	windows_aarch64_msvc@0.52.6
	windows_i686_gnu@0.52.6
	windows_i686_gnullvm@0.52.6
	windows_i686_msvc@0.52.6
	windows_x86_64_gnu@0.52.6
	windows_x86_64_gnullvm@0.52.6
	windows_x86_64_msvc@0.52.6
"

inherit cargo git-r3

DESCRIPTION="Language Server Protocol implementation for systemd unit files"
HOMEPAGE="https://github.com/jfryy/systemd-lsp"
EGIT_REPO_URI="${HOMEPAGE}.git"
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+=" Apache-2.0 MIT Unicode-3.0"
SLOT="0"
KEYWORDS="~amd64"
src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}
