# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.0

EAPI=8

CRATES="
	aho-corasick@0.7.18
	bitflags@1.3.2
	cc@1.0.70
	cfg-if@1.0.0
	crossbeam-channel@0.5.1
	crossbeam-utils@0.8.5
	form_urlencoded@1.0.1
	home@0.5.3
	idna@0.2.3
	itoa@0.4.8
	lazy_static@1.4.0
	log@0.4.14
	lsp-server@0.5.2
	lsp-types@0.89.2
	matches@0.1.9
	memchr@2.4.1
	percent-encoding@2.1.0
	proc-macro2@1.0.29
	quote@1.0.9
	regex-syntax@0.6.25
	regex@1.5.4
	ryu@1.0.5
	serde@1.0.130
	serde_derive@1.0.130
	serde_json@1.0.67
	serde_repr@0.1.7
	syn@1.0.75
	tinyvec@1.3.1
	tinyvec_macros@0.1.0
	tree-sitter-openscad@0.2.0
	tree-sitter@0.20.0
	unicode-bidi@0.3.6
	unicode-normalization@0.1.19
	unicode-xid@0.2.2
	url@2.2.2
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
"

inherit cargo git-r3

DESCRIPTION="A Language Server Protocol server for OpenSCAD"
HOMEPAGE="https://github.com/dzhu/openscad-language-server"
SRC_URI="
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	MIT
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"
EGIT_REPO_URI="${HOMEPAGE}".git

src_unpack() {
    git-r3_src_unpack
    cargo_live_src_unpack
}
